name: Deploy to GCP

on:
  push:
    branches-ignore: "master"

jobs:
  build:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil cp -r _site gs://j-volpe-com/${GITHUB_REF:11}
