name: Deploy to GCP

on:
  push:
    branches-ignore: "master"

jobs:
  build:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Setup Google Cloud SDK
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} > ./gcloud-service-key.json
          gcloud auth activate-service-account \
            --key-file=./gcloud-service-key.json
          gcloud --quiet config set project ${GCP_PROJECT_ID}
      - run: gsutil rsync _site/ gs://j-volpe-com/_site
