name: Clean up deployed branches in GCP
on: [delete]

jobs:
  build:
    name: Clean up deployed branches in GCP
    runs-on: ubuntu-latest
    steps:
      - name: Clean up deployed branches in GCP
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil rm -rf gs://j-volpe-com/${{ github.event.ref }}
